In [15]:
import re
import glob
import pandas as pd 
from pandasql import sqldf
#import library
import pandas as pd 
import json
from pandasql import sqldf
from sqlalchemy import create_engine

In [3]:

#Connect database
connection_string = 'mysql+pymysql://minhdung:020920@localhost/School'

engine = create_engine(connection_string)

conn = engine.connect()

In [21]:
def filter_files(file_name):
    pattern = '([^.]*)(10A|11B|12C)([0-9]{1}|[0-9]{2}).json'
    return bool(re.search(pattern, file_name))


class_name_pattern = '(10|11|12)A([0-9]*)'
folder_path = "../Generator/Data/**/*.json"

def extract_score(df,scores):
    for key,value in scores.items():
        df[key] = value
    return None

for item in filter(filter_files, glob.glob(folder_path, recursive = True)):
    class_name_index = re.search(class_name_pattern, item).span()
    class_name = item[class_name_index[0]:class_name_index[1]]
    df = pd.read_json(item)
    df['class name'] = class_name
    df1 = pd.json_normalize(df['Score'], max_level=0)
    df = pd.concat([df.drop(columns = 'Score'), df1], axis=0)
    df.to_sql('LeQuyDon_students', conn, if_exists= 'append')

    School ID  Class ID   average    rank class name      Math    Physic  \
0        45.0       0.0  3.896658    weak       10A8       NaN       NaN
1        45.0       1.0  7.521086  medium       10A8       NaN       NaN
2        45.0       2.0  0.090840    weak       10A8       NaN       NaN
3        45.0       3.0  6.963646  medium       10A8       NaN       NaN
4        45.0       4.0  0.666066    weak       10A8       NaN       NaN
..        ...       ...       ...     ...        ...       ...       ...
31        NaN       NaN       NaN     NaN        NaN  3.926456  4.083371
32        NaN       NaN       NaN     NaN        NaN  5.385965  5.386409
33        NaN       NaN       NaN     NaN        NaN  9.961936  9.951151
34        NaN       NaN       NaN     NaN        NaN  8.004724  7.834739
35        NaN       NaN       NaN     NaN        NaN  5.136642  5.137290

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
31   3.926474    3.738906  3.926456    3.880698  3.926321   3.926455
32   8.412223    5.198277  4.699800    5.386059  5.385921   5.315325
33   9.961989    9.970201  9.961872    9.961909  9.961873   9.961873
34   7.826532    7.826476  7.814425    7.826399  6.588652   7.826532
35   5.166493    5.643775  5.136744    3.031116  5.139810   6.210688

    Common Sense  Computer
0            NaN       NaN
1            NaN       NaN
2            NaN       NaN
3            NaN       NaN
4            NaN       NaN
..           ...       ...
31      3.926465  4.002960
32      5.385552  3.303682
33      9.964051  9.961873
34      8.890304  7.826538
35      5.627813  5.136708

[72 rows x 15 columns]
    School ID  Class ID  rank   average class name      Math    Physic  \
0        31.0       0.0  good  8.802172      10A13       NaN       NaN
1        31.0       1.0  weak  0.180905      10A13       NaN       NaN
2        31.0       2.0  weak  4.988158      10A13       NaN       NaN
3        31.0       3.0  good  9.142616      10A13       NaN       NaN
4        31.0       4.0  weak  3.157254      10A13       NaN       NaN
..        ...       ...   ...       ...        ...       ...       ...
26        NaN       NaN   NaN       NaN        NaN  4.699473  7.286900
27        NaN       NaN   NaN       NaN        NaN  9.825863  9.869708
28        NaN       NaN   NaN       NaN        NaN  6.538774  6.540002
29        NaN       NaN   NaN       NaN        NaN  6.714237  6.731081
30        NaN       NaN   NaN       NaN        NaN  8.432118  8.432138

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
26   5.087436    4.845895  4.699473    4.699580  4.702296   1.124714
27   9.869694    9.869700  9.868699    9.869733  9.869700   9.869714
28   6.335079    8.494563  6.540005    5.745701  6.540004   6.540007
29   8.537171    6.731792  6.726158    6.317519  6.671940   5.424859
30   8.481525    8.880903  8.438061    7.988282  8.437495   8.432137

    Common Sense  Computer
0            NaN       NaN
1            NaN       NaN
2            NaN       NaN
3            NaN       NaN
4            NaN       NaN
..           ...       ...
26      5.134310  4.714653
27      9.914661  9.869529
28      5.585670  6.540209
29      6.731371  6.731790
30      8.432918  8.365795

[62 rows x 15 columns]
    School ID  Class ID    rank   average class name      Math    Physic  \
0        14.0       0.0  medium  7.419443      10A16       NaN       NaN
1        14.0       1.0  medium  7.689193      10A16       NaN       NaN
2        14.0       2.0    weak  4.863909      10A16       NaN       NaN
3        14.0       3.0    weak  1.388556      10A16       NaN       NaN
4        14.0       4.0  medium  7.754376      10A16       NaN       NaN
..        ...       ...     ...       ...        ...       ...       ...
28        NaN       NaN     NaN       NaN        NaN  7.985029  6.788263
29        NaN       NaN     NaN       NaN        NaN  4.920726  4.914603
30        NaN       NaN     NaN       NaN        NaN  9.111543  9.111547
31        NaN       NaN     NaN       NaN        NaN  7.576072  7.630632
32        NaN       NaN     NaN       NaN        NaN  4.389381  3.547996

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
28   5.857691    6.787174  6.741741    6.788253  6.356934   7.003024
29   4.947738    4.947742  4.175398    7.058632  4.002994   4.814909
30   9.096234    9.111547  9.431655    9.119876  9.110047   9.074800
31   7.630632    7.630651  7.546908    7.630637  7.648523   7.630632
32   4.475081    4.389381  4.413861    4.389380  4.711669   4.389284

    Common Sense  Computer
0            NaN       NaN
1            NaN       NaN
2            NaN       NaN
3            NaN       NaN
4            NaN       NaN
..           ...       ...
28      6.786162  6.788263
29      4.826696  4.867980
30      9.111547  8.836674
31      7.679598  7.702038
32      4.380317  4.807457

[66 rows x 15 columns]
    School ID  Class ID  rank   average class name      Math    Physic  \
0        34.0       0.0  good  8.656457      10A12       NaN       NaN
1        34.0       1.0  weak  1.665393      10A12       NaN       NaN
2        34.0       2.0  good  9.546169      10A12       NaN       NaN
3        34.0       3.0  good  8.150764      10A12       NaN       NaN
4        34.0       4.0  good  8.366479      10A12       NaN       NaN
..        ...       ...   ...       ...        ...       ...       ...
28        NaN       NaN   NaN       NaN        NaN  3.618879  8.317352
29        NaN       NaN   NaN       NaN        NaN  8.522943  8.527041
30        NaN       NaN   NaN       NaN        NaN  8.901448  8.899552
31        NaN       NaN   NaN       NaN        NaN  4.755804  4.167435
32        NaN       NaN   NaN       NaN        NaN  7.674997  7.675520

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
28   4.660326    5.171310  2.805873    3.469098  4.660325   4.579430
29   8.474631    8.474675  8.411462    8.474675  8.405879   7.690776
30   8.392226    8.899552  8.899553    9.323877  8.975401   8.898577
31   4.749891    4.749516  5.384471    4.750067  4.749671   4.751209
32   7.910621    7.701971  7.675702    7.952423  7.745078   7.675472

    Common Sense  Computer
0            NaN       NaN
1            NaN       NaN
2            NaN       NaN
3            NaN       NaN
4            NaN       NaN
..           ...       ...
28      4.660324  4.660324
29      8.477767  9.286896
30      8.905674  8.899660
31      4.687581  4.749516
32      7.675319  7.067620

[66 rows x 15 columns]
    School ID  Class ID    rank   average class name      Math    Physic  \
0        55.0       0.0    good  8.002701       10A1       NaN       NaN
1        55.0       1.0    good  9.377819       10A1       NaN       NaN
2        55.0       2.0  medium  6.931314       10A1       NaN       NaN
3        55.0       3.0    weak  4.843834       10A1       NaN       NaN
4        55.0       4.0    good  8.303868       10A1       NaN       NaN
..        ...       ...     ...       ...        ...       ...       ...
29        NaN       NaN     NaN       NaN        NaN  6.515529  6.514489
30        NaN       NaN     NaN       NaN        NaN  5.564053  6.700076
31        NaN       NaN     NaN       NaN        NaN  9.009823  9.010828
32        NaN       NaN     NaN       NaN        NaN  9.376123  5.642523
33        NaN       NaN     NaN       NaN        NaN  4.549715  4.974344

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
29   6.142935    7.078291  6.321936    6.515567  6.547975   6.515586
30   5.567860    4.990481  5.392582    5.567868  5.567860   5.557639
31   9.003533    9.034210  9.009823    8.976083  9.010073   9.043975
32   5.548757    5.642503  5.642503    5.640325  4.682240   3.837383
33   4.975215    5.100059  5.016138    4.977958  4.974159   5.220995

    Common Sense  Computer
0            NaN       NaN
1            NaN       NaN
2            NaN       NaN
3            NaN       NaN
4            NaN       NaN
..           ...       ...
29      6.515591  6.488011
30      5.567877  5.202300
31      9.009823  8.990060
32      4.676628  5.736041
33      4.974788  4.978191

[68 rows x 15 columns]
    School ID  Class ID   average    rank class name      Math    Physic  \
0        51.0       0.0  0.545482    weak       10A4       NaN       NaN
1        51.0       1.0  6.986264  medium       10A4       NaN       NaN
2        51.0       2.0  8.165431    good       10A4       NaN       NaN
3        51.0       3.0  5.413470    weak       10A4       NaN       NaN
4        51.0       4.0  7.317332  medium       10A4       NaN       NaN
..        ...       ...       ...     ...        ...       ...       ...
27        NaN       NaN       NaN     NaN        NaN  4.646201  4.645845
28        NaN       NaN       NaN     NaN        NaN  8.366230  8.456661
29        NaN       NaN       NaN     NaN        NaN  4.294509  5.522461
30        NaN       NaN       NaN     NaN        NaN  9.915213  9.918578
31        NaN       NaN       NaN     NaN        NaN  4.941500  4.970188

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
27   4.647305    6.728597  4.834160    4.648514  4.646144   4.645847
28   8.425383    8.272403  8.458955    8.365837  7.857643   8.365834
29   5.714797    4.294524  4.308912    4.295711  4.294509   4.333124
30   9.918578    9.918578  9.918578    9.918616  9.919178   9.919814
31   4.941548    7.557283  4.941520    2.306183  4.941500   4.940415

    Common Sense  Computer
0            NaN       NaN
1            NaN       NaN
2            NaN       NaN
3            NaN       NaN
4            NaN       NaN
..           ...       ...
27      2.370399  4.645442
28      8.723539  8.365878
29      2.221899  3.664646
30      9.918579  9.920068
31      5.032866  4.841995

[64 rows x 15 columns]
    School ID  Class ID   average  rank class name      Math    Physic  \
0        54.0       0.0  4.285252  weak       10A2       NaN       NaN
1        54.0       1.0  9.440757  good       10A2       NaN       NaN
2        54.0       2.0  2.671446  weak       10A2       NaN       NaN
3        54.0       3.0  1.264095  weak       10A2       NaN       NaN
4        54.0       4.0  3.554111  weak       10A2       NaN       NaN
..        ...       ...       ...   ...        ...       ...       ...
29        NaN       NaN       NaN   NaN        NaN  4.105426  6.523144
30        NaN       NaN       NaN   NaN        NaN  2.039311  2.771087
31        NaN       NaN       NaN   NaN        NaN  8.433538  9.723228
32        NaN       NaN       NaN   NaN        NaN  5.959954  5.993952
33        NaN       NaN       NaN   NaN        NaN  5.195484  5.264049

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
29   8.609155    6.696506  6.523021    6.525880  6.523161   6.523765
30   2.039319    2.103338  2.046703    2.031325  2.039323   1.289441
31   8.433390    8.433550  8.433526    8.429595  7.385425   8.440843
32   5.867295    5.953355  5.984864    8.036036  5.953355   5.953441
33   5.505687    5.274236  6.104268    5.214783  5.194080   5.202085

    Common Sense  Computer
0            NaN       NaN
1            NaN       NaN
2            NaN       NaN
3            NaN       NaN
4            NaN       NaN
..           ...       ...
29      6.541543  6.658608
30      2.084163  1.949178
31      8.405351  8.217062
32      5.964896  3.866389
33      5.194152  3.792692

[68 rows x 15 columns]
    School ID  Class ID    rank   average class name      Math    Physic  \
0        37.0       0.0  medium  7.793635      10A10       NaN       NaN
1        37.0       1.0  medium  7.345116      10A10       NaN       NaN
2        37.0       2.0    good  9.614353      10A10       NaN       NaN
3        37.0       3.0    weak  4.282149      10A10       NaN       NaN
4        37.0       4.0  medium  7.714277      10A10       NaN       NaN
..        ...       ...     ...       ...        ...       ...       ...
29        NaN       NaN     NaN       NaN        NaN  6.362394  7.481350
30        NaN       NaN     NaN       NaN        NaN  6.776508  5.346530
31        NaN       NaN     NaN       NaN        NaN  8.144590  8.164320
32        NaN       NaN     NaN       NaN        NaN  7.166004  6.975578
33        NaN       NaN     NaN       NaN        NaN  3.543969  4.049496

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
29   6.348567    5.883653  6.340382    6.364793  6.642097   6.362392
30   5.346498    5.370087  5.344559    5.151327  4.086229   5.346513
31   8.145175    8.275108  8.186806    7.520647  8.157671   8.201416
32   7.174470    7.174332  7.174488    7.151819  7.200959   7.174490
33   3.800003    3.959213  5.411526    4.051640  4.038831   4.051405

    Common Sense  Computer
0            NaN       NaN
1            NaN       NaN
2            NaN       NaN
3            NaN       NaN
4            NaN       NaN
..           ...       ...
29      6.361834  5.476477
30      5.343858  5.352874
31      8.144576  8.505451
32      7.330839  7.221925
33      4.045686  3.564632

[68 rows x 15 columns]
    School ID  Class ID   average    rank class name      Math    Physic  \
0        52.0       0.0  1.764316    weak       10A3       NaN       NaN
1        52.0       1.0  7.155430  medium       10A3       NaN       NaN
2        52.0       2.0  6.278132    weak       10A3       NaN       NaN
3        52.0       3.0  9.475694    good       10A3       NaN       NaN
4        52.0       4.0  5.172147    weak       10A3       NaN       NaN
..        ...       ...       ...     ...        ...       ...       ...
28        NaN       NaN       NaN     NaN        NaN  8.262230  8.903326
29        NaN       NaN       NaN     NaN        NaN  5.404129  5.488383
30        NaN       NaN       NaN     NaN        NaN  7.987385  8.875434
31        NaN       NaN       NaN     NaN        NaN  9.215977  9.215980
32        NaN       NaN       NaN     NaN        NaN  7.647861  8.092186

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
28   8.945703    8.947549  9.584487    8.947303  8.945703   9.044281
29   5.405683    4.659415  5.404128    5.476639  5.466851   5.404649
30   7.971472    8.003552  7.996351    7.165263  8.003553   8.002130
31   9.211325    9.215980  8.988600    9.215980  9.215980   9.262381
32   8.269723    8.272402  9.079904    8.272685  8.272916   8.272673

    Common Sense  Computer
0            NaN       NaN
1            NaN       NaN
2            NaN       NaN
3            NaN       NaN
4            NaN       NaN
..           ...       ...
28      8.947549  8.947357
29      5.927512  5.403891
30      8.026827  8.003552
31      9.197127  9.420472
32      8.273190  8.273181

[66 rows x 15 columns]
    School ID  Class ID   average  rank class name      Math    Physic  \
0        48.0       0.0  6.443218  weak       10A5       NaN       NaN
1        48.0       1.0  4.400505  weak       10A5       NaN       NaN
2        48.0       2.0  4.177008  weak       10A5       NaN       NaN
3        48.0       3.0  1.726476  weak       10A5       NaN       NaN
4        48.0       4.0  8.710634  good       10A5       NaN       NaN
..        ...       ...       ...   ...        ...       ...       ...
28        NaN       NaN       NaN   NaN        NaN  6.461215  6.602770
29        NaN       NaN       NaN   NaN        NaN  5.255179  4.499480
30        NaN       NaN       NaN   NaN        NaN  2.346346  2.348231
31        NaN       NaN       NaN   NaN        NaN  5.170903  8.215311
32        NaN       NaN       NaN   NaN        NaN  3.386459  2.198966

    Chemistry  Literature   History  Geographic   English  Technique  \
0         NaN         NaN       NaN         NaN       NaN        NaN
1         NaN         NaN       NaN         NaN       NaN        NaN
2         NaN         NaN       NaN         NaN       NaN        NaN
3         NaN         NaN       NaN         NaN       NaN        NaN
4         NaN         NaN       NaN         NaN       NaN        NaN
..        ...         ...       ...         ...       ...        ...
28   6.530183    6.232226  6.467166    6.878533  6.041389   6.476411
29   4.499480    4.511510  4.499728    3.339598  4.499480   4.768682